### PR TITLE
run npm update

### PR DESCRIPTION
**Pull request by briangough**
### Description

Update npm packages with `npm update` and `npm install`

Notable update aws-sdk 2.315.0 -> 2.628.0

#### Screenshots

NA

#### Related Issues / PRs

?

### Review

No changes to package.json, just updates with compatible versions.

https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#23810
2.381.0 bugfix: S3: fix putObject using stream <1mb
https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#23680
2.368.0 bugfix: md5: enable SDK to calculate content MD5 for more new S3 operations

#### Potential Impact

Low

#### Manual Testing Performed

- [ ] Unit and acceptance tests 

#### Accessibility

NA

### Deployment

NA

#### Deployment Checklist

NA

#### Metrics and Monitoring

NA

#### Who Needs to Know?

 @gh2k  here is the change from running npm update.

### CODE REVIEW

**Comment by briangough** [comment]
I had to update the unit tests for the settings, something to do with the `require` of `settings-sharelatex`  inside a mocha test.  I've used SandboxedModule, which works.  I am not sure exactly why it was failing with  the error below but the test was fragile like that any way, because the it would only work if that was the first time the `require('settings-sharelatex')` was called - otherwise it would just return the cache version of the module.

```
       s3
         should use JSONified env var if present:
     TypeError: In /app/node_modules/settings-sharelatex/Settings.coffee, child.updateLocationDataIfMissing is not a function
      at /app/node_modules/coffee-script/lib/coffee-script/nodes.js:244:22
      at Value.exports.Base.Base.eachChild (node_modules/coffee-script/lib/coffee-script/nodes.js:189:17)
      at Value.exports.Base.Base.updateLocationDataIfMissing (node_modules/coffee-script/lib/coffee-script/nodes.js:243:19)
      at /app/node_modules/coffee-script/lib/coffee-script/helpers.js:104:13
      at Object.anonymous (node_modules/coffee-script/lib/coffee-script/parser.js:146:54)
      at Parser.parse (node_modules/coffee-script/lib/coffee-script/parser.js:567:36)
      at compile (node_modules/coffee-script/lib/coffee-script/coffee-script.js:60:27)
      at Object.loadFile (node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:28)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

**Comment by das7pad** [comment]
This is likely conflicting with https://github.com/overleaf/filestore/pull/96.

**Comment by gh2k** [comment]
I'd like to pull this one in for now as it has the potential to solve a more immediate problem and is a smaller change.

**Comment by das7pad** [comment]
> 2.381.0 bugfix: fix putObject using stream <1mb
> 2.368.0 bugfix: md5: enable SDK to calculate content MD5 for more new S3 operations

If we depend on these patch-levels for our app to work correctly, then let's bump the minimal version in the package.json too.

**Comment by das7pad** [comment]
prettier is failing to run locally. This repository is not linted in CI.

```
$ make format     
BUILD_NUMBER=local BRANCH_NAME=jpa-dependencies-cleanup PROJECT_NAME=filestore MOCHA_GREP= docker-compose -f docker-compose.yml run --rm test_unit npm run format

> filestore-sharelatex@0.1.4 format /app
> prettier-eslint '**/*.js' --list-different

prettier-eslint [ERROR]: There was trouble creating the ESLint CLIEngine.
prettier-eslint-cli [ERROR]: There was an error formatting "app.js": 
    AssertionError [ERR_ASSERTION]: 'basePath' should be an absolute path.
        at new IgnorePattern (/app/node_modules/eslint/lib/cli-engine/config-array/ignore-pattern.js:178:9)
        at ConfigArrayFactory._normalizeObjectConfigDataBody (/app/node_modules/eslint/lib/cli-engine/config-array-factory.js:653:49)
        at _normalizeObjectConfigDataBody.next (<anonymous>)
        at ConfigArrayFactory._normalizeObjectConfigData (/app/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
        at _normalizeObjectConfigData.next (<anonymous>)
        at createConfigArray (/app/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
        at ConfigArrayFactory.create (/app/node_modules/eslint/lib/cli-engine/config-array-factory.js:395:16)
        at createBaseConfigArray (/app/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:96:48)
        at new CascadingConfigArrayFactory (/app/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:211:30)
        at new CLIEngine (/app/node_modules/eslint/lib/cli-engine/cli-engine.js:563:36)
prettier-eslint [ERROR]: There was trouble creating the ESLint CLIEngine.
prettier-eslint-cli [ERROR]: There was an error formatting "app/js/Errors.js": 
....
```

**Pull request merged**
