### PR TITLE
Get filestore building with node 10.14.1

### PR DESCRIPTION
**Pull request by mans0954**
Contributes to: https://github.com/overleaf/sharelatex/issues/1118

### CODE REVIEW

**Comment by henryoswald** [comment]
looks liks CI is failing.

**Comment by mans0954** [comment]
Yes. I spent a bit of time looking at it this morning. I think it's connected to the enabled conversions, but it wasn't obvious to me how to fix it so I moved on.

**Comment by das7pad** [comment]
I do not have access your CI results, but the tests probably timeout after a log entry with the message `sending file to response`.

See my PR #49 for an explaination and a fix.

**Comment by henryoswald** [comment]
closing to stop alerts

**Pull request closed without merging**
